backend:
  name: git-gateway
  repo: recrea-t/recreat
  branch: main

media_folder: static/images
public_folder: /images

site_url: https://www.recreat.cat
display_url: https://www.recreat.cat
logo_url: https://www.recreat.cat/images/logo.svg
locale: "ca"

collections:
  - name: "pages"
    label: "Pàgines"
    files:
      - file: "src/pages/index.md"
        label: "Pàgina d'inici"
        name: "index"
        fields:
          - {label: "Template Key", name: "templateKey", widget: "hidden"}
          - {label: "Títol de la pàgina (SEO)", name: "title", widget: "string"}
          - {label: "Descripció de la pàgina (SEO)", name: "description", widget: "string"}
          - {label: "Serveis", name: "serveis", widget: "list", fields: [{label: "Id", name: "id", widget: "hidden"}, {label: "Nom", name: "nom", widget: "string"}, {label: "Descripció", name: "descripcio", widget: "string"}, {label: "Imatge", name: "imatge", widget: "image"}]}
